### ISSUE TITLE
Is it possible of supporting macOS 12 Monterey or newer version.

### ISSUE THREAD

**Issue by PinoTucana** [xiaozhuai/odourless#13]
RT，是否会继续开发 odourless 以支持新版 macOS，谢谢。

**Comment by XP1** [comment]
Works for me on macOS 14.2.1 (23C71) Sonoma.

* Mac mini 2012 (Macmini6,2)
* macOS 14.2.1 (23C71) Sonoma
* OpenCore Legacy Patcher 1.3.0

If you get an "inject failed, Unable to access process with pid 000 from the current user account" error, make sure System Integrity Protection (SIP) is disabled.

```
user@Users-Mac-mini ~ % csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: disabled
	NVRAM Protections: disabled
	BaseSystem Verification: disabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
user@Users-Mac-mini ~ % 
```

If not using OpenCore, boot into recovery mode or installer and then run "`csrutil disable`".

If you are using OpenCore Legacy Patcher, go to Settings > Security > Under "System Integrity Protection", enable the checkboxes:

![Screenshot 2024-01-20 at 12 07 04 AM](https://github.com/xiaozhuai/odourless/assets/776585/0d6e4428-e356-4bc1-a132-aadc6087c5e4)

Return > Build and Install OpenCore.

**Comment by PinoTucana** [comment]
Thanks, @XP1 
I have tested with disable SIP using OCLP 1.4.1, odourless worked.
And I also tested several other times and noticed there's one SIP Value odourless uses.
With:
* MacBook Pro (Retina, 15-inch, Mid 2015) (MacBookPro11,4)
* macOS Ventura Version 13.6.3 (Build 22G436)

----
Default,
`ALLOW_UNTRUSTED_KEXTS`(value: `0x1`),
`ALLOW_UNRESTRICTED_FS`(value: `0x2`) and
`ALLOW_UNAUTHENTICATED_ROOT`(value: `0x800`)
are selected, SIP value will be set to `0x803`.

Select all SIP values will totally disable SIP.
But I'd like to keep SIP partially disabled. So I tested every SIP value.
I found
`ALLOW_TASK_FOR_PID`(value: `0x4`)
is the key SIP value for odourless.
Only if it is selected, odourless works.

----
The result is I selected the 4 values mentioned above. Set SIP value to `0x807`. odourless worked.
![image](https://github.com/xiaozhuai/odourless/assets/10352574/111c40c1-2228-439f-ad8b-47c64f718315)

**Comment by PinoTucana** [comment]
With disable SIP, macOS 13(Ventura) & macOS 14(Sonoma) are all tested odourless worked.
So I think macOS 12(Monterey) will also be fine and close this issue.
If someone occurs odourless not work after macOS update, be welcome to reopen this issue.
