### ISSUE TITLE
Problems with Odourless Installation

### ISSUE THREAD

**Issue by noib3** [xiaozhuai/odourless#3]
macOS version: macOS Catalina 10.15.7
output of `csrutil status`: `System Integrity Protection status: disabled.`

I tried to follow the installation instructions:

1. I downloaded the zipped file from the release page and unzipped it;
2. I moved `Odourless.app` to `/Applications`.

But if I try to open it, either via Spotlight or by clicking the icon through Finder, I get the error `Installation Check .. You must install this application under /Appplications`, even though it already is under `/Applications`!

![2020-Dec-09@13:29:14](https://user-images.githubusercontent.com/59321248/101630051-9bac6e00-3a22-11eb-99fc-c27274f0e9f2.png)

I then tried manually installing it with this bash script

```bash
local path_resources="/Applications/Odourless.app/Contents/Resources"
cat "$path_resources/odourless-daemon.plist" \
| sed "s#___replace_me_daemon_path__#$path_resources/bin/odourless-daemon#" \
| sudo tee /Library/LaunchDaemons/odourless-daemon.plist &>/dev/null

launchctl load "/Library/LaunchDaemons/odourless-daemon.plist"
```

which runs without errors. After rebooting, if I manually launch Odourless with
```
/Applications/Odourless.app/Contents/MacOS/odourless
```
I can see that the daemon is installed and running
![2020-Dec-09@13:36:21](https://user-images.githubusercontent.com/59321248/101630967-e4185b80-3a23-11eb-9657-2290f1dae07a.png)

However Odourless doesn't seem to work, Finder still created `.DS_Store` files, as you can see in this gif

![output](https://user-images.githubusercontent.com/59321248/101631998-871da500-3a25-11eb-9733-7cb1a5b97bab.gif)

**Comment by xiaozhuai** [comment]
Hello @noib3 , will you provide `/tmp/odourless-inject.log` and `/tmp/odourless-daemon.log`?

**Comment by noib3** [comment]
Here you go: [odourless-daemon.log](https://wtools.io/paste-code/b2Rp) and [odourless-inject.log](https://wtools.io/paste-code/b2Rq).

**Comment by xiaozhuai** [comment]
@noib3 I've release a new version 0.0.5, would you please try this? And check logs.
`tail -f /usr/local/var/.odourless_cage/daemon.log`, `tail -f /usr/local/var/.odourless_cage/inject.log`

**Comment by xiaozhuai** [comment]
@noib3 Hey bro, does it work now?    : )
Waiting for your further feedback.

**Comment by noib3** [comment]
@xiaozhuai Sorry I was a little busy yesterday. I'm still experiencing the same issues even with version 0.0.6. The GUI interface still says that Odourless should be placed in /Applications even if it already is, and .DS_Store files are still created when I start Finder.

However I noticed that when I quit Finder they are deleted. Is Odourless supposed to delete .DS_Store files after the Finder creates them or is it supposed to prevent Finder from creating them? If it's the first one then it works.

**Comment by xiaozhuai** [comment]
@noib3 Never mind : )
Odourless would not search and delete .DS_Store files that already exists. However, it move .DS_Store file to cage when Finder access it next time. And if Finder wants to create a new one .DS_Store, it will be in cage directory.

So you can delete .DS_Store manually. `sudo find / -name ".DS_Store" -delete`
Or just let Odourless handle it, all .DS_Store will be in cage directory, finally.

And the installation check, I don't know why it happen. I am on 10.15.7 too, and it works fine.
Would you please compile Odourless by yourself and check file `src/gui/odourless.cpp` func `OdourlessApp::OnInit`?
It's pretty easy to build Odourless, just follow the instruction.
Thanks!

**Comment by noib3** [comment]
> And if Finder wants to create a new one .DS_Store, it will be in cage directory.

Then it doesn't work. After I open Finder a new .DS_Store file is created, but it gets moved to the cage directory if I quit Finder. If I understood how Odourless works correctly, the .DS_Store file should've been created in the cage directory in the first place.

I compiled Odourless from source, this is the content of `src/gui/odourless.cpp`:

```cpp
//
// Created by xiaozhuai on 2019/12/12.
//

#include "Log.h"
#include "MainFrame.h"

#include <wx/wx.h>
#include <OdourlessUtils.h>
#include <ProcessHelper.h>


class OdourlessApp : public wxApp {

public:
    OdourlessApp()
            : wxApp(),
              m_mainFrame(nullptr) {
        Log::init();
    }

    ~OdourlessApp() override {
        Log::destroy();
    }

    bool OnInit() override {
        if(OdourlessUtils::checkSIPEnabled()) {
            wxMessageBox("You must disable SIP to use this application", "SIP Check", wxOK | wxICON_ERROR);
            Exit();
            return false;
        }

#ifdef ODOURLESS_MUST_INSTALL_TO_APPLICATIONS
        if(ProcessHelper::getCurrentExecutablePath() != ODOURLESS_INSTALL_PATH "/Contents/MacOS/odourless") {
            wxMessageBox("You must install this application under /Applications", "Installation Check", wxOK | wxICON_ERROR);
            Exit();
            return false;
        }
#endif

        m_mainFrame = new MainFrame();
        m_mainFrame->Show(true);
        return true;
    }

private:
    MainFrame *m_mainFrame;
};

wxIMPLEMENT_APP(OdourlessApp);
```

**Comment by xiaozhuai** [comment]
@noib3 If you compile it from source, then everything seems to work fine? So strange...

**Comment by xiaozhuai** [comment]
@noib3 I make a testing version, would you please run this to help me figure out installation issue? Thanks!
It will show a message box print executable path. [Odourless_0.0.6_for_testing.zip](https://github.com/xiaozhuai/odourless/files/5686155/Odourless_0.0.6_for_testing.zip)

![image](https://user-images.githubusercontent.com/4773701/102034596-5f4d8900-3df9-11eb-93f4-fc2a5badb590.png)

**Comment by xiaozhuai** [comment]
@noib3 Hi bro! Merry Christmas! I've release Odourless 0.0.7, and it will be helpful if you can give it a try. Thanks~~

**Comment by noib3** [comment]
@xiaozhuai I've tested version 0.0.7 and everything seems to be working fine. I no longer get an error when trying to launch via GUI.

**Comment by xiaozhuai** [comment]
@noib3 Glad to hear that : )
